security:
  encoders:
    App\Entity\User: bcrypt
    Symfony\Component\Security\Core\User\User: plaintext

  providers:
    chain_provider:
      chain:
        providers: [ in_memory, app_user_provider ]
    in_memory:
      memory:
        users:
          admin@lgorycrb.ru: { password: 'admin', roles: [ ROLE_ADMIN, ROLE_USER ] }
    app_user_provider:
      entity:
        class: 'App\Entity\User'
        property: 'email'
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: true
      provider: chain_provider
      guard:
        authenticators:
          - App\Security\LoginFormAuthenticator
      logout:
        path: app_logout

  access_control:
    - { path: ^/user/create/doctor, roles: [ IS_AUTHENTICATED_FULLY ] }
    - { path: ^/user/register, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
    - { path: ^/user/create, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
    - { path: ^/post/\d+/view, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
    - { path: ^/post, roles: [ IS_AUTHENTICATED_FULLY ] }
    - { path: ^/user, roles: [ IS_AUTHENTICATED_FULLY ] }
    - { path: ^/appointment, roles: [ IS_AUTHENTICATED_FULLY ] }
    - { path: ^/profile, roles: [ IS_AUTHENTICATED_FULLY ] }
    - { path: ^/, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
